/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author evrob0095
 */
public class quoteGenerator extends javax.swing.JFrame {

    /**
     * Creates new form quoteGenerator
     */
    public quoteGenerator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        instructionLabel = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        quoteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionLabel.setFont(new java.awt.Font("Ti89pc", 0, 12)); // NOI18N
        instructionLabel.setText("Click button to get a quote");
        jPanel1.add(instructionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, 20));

        generateButton.setText("Generate Quote");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(generateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        titleLabel.setFont(new java.awt.Font("Ti89pc", 0, 18)); // NOI18N
        titleLabel.setText("Quotation generator to make you feel better about yourself");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        quoteLabel.setFont(new java.awt.Font("Ti89pc", 0, 12)); // NOI18N
        quoteLabel.setText("boop de woop, scoop de woop, woopity woop doop boop");
        jPanel1.add(quoteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        int randomQuote = (int)Math.round(Math.random()*7+1);
        switch (randomQuote) {
            case 1:
                quoteLabel.setText("Sometimes when I close my eyes, I can't see");
                break;
            case 2:
                quoteLabel.setText("What happens when your heart just stops?      You die...");
                break;
            case 3:
                quoteLabel.setText("Don't take a bullet for anyone, if you have time to jump in front of the bullet they time to get the heck out of the way");
                break;
            case 4:
                quoteLabel.setText("You know it's cold outside when you go outside and its... cold");
                break;
            case 5:
                quoteLabel.setText("If you spell Alabama backwards, you can rearrange the letters to spell Alabama");
                break;
            case 6:
                quoteLabel.setText("Home is where we live");
                break;
            case 7:
                quoteLabel.setText("Name something Russia is famous for.        *Russians* ");
                break;
            default:
                quoteLabel.setText("If you turn an hourglass on it's side it becomes an infinity symbol and time stops ticking");
                
        }
        
                
    }//GEN-LAST:event_generateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quoteGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quoteGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quoteGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quoteGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quoteGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel quoteLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
